# Generated by Django 6.0.4 on 2026-04-16 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('igihozo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['user__username'], 'permissions': [('view_privileged_dashboard', 'Can view the privileged dashboard')]},
        ),
    ]
