# Generated by Django 6.0.4 on 2026-04-14 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webwi', '0003_loginattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
