# Generated by Django 6.0.4 on 2026-04-15 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antoine', '0002_loginattempt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('REGISTRATION', 'User Registration'), ('LOGIN_SUCCESS', 'Login Success'), ('LOGIN_FAILURE', 'Login Failure'), ('LOGOUT', 'Logout'), ('PASSWORD_CHANGE', 'Password Change'), ('PASSWORD_RESET_REQUEST', 'Password Reset Request'), ('PASSWORD_RESET_CONFIRM', 'Password Reset Confirmed'), ('PERMISSION_CHANGE', 'Permission/Role Change'), ('PROFILE_UPDATE', 'Profile Update'), ('ADMIN_ACTION', 'Admin Action'), ('ACCOUNT_LOCK', 'Account Lock'), ('ACCOUNT_UNLOCK', 'Account Unlock')], help_text='Type of security event', max_length=50)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', help_text='Severity level of the event', max_length=10)),
                ('ip_address', models.GenericIPAddressField(help_text='IP address where event originated')),
                ('user_agent', models.TextField(blank=True, help_text='User agent string of the client')),
                ('description', models.TextField(help_text='Detailed description of the event')),
                ('details', models.JSONField(blank=True, default=dict, help_text='Structured data about the event (never contains passwords or secrets)')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When the event occurred')),
                ('affected_user', models.ForeignKey(blank=True, help_text='User affected by the event (may differ from user for admin actions)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs_affected', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, help_text='User who triggered the event', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='antoine_aud_user_id_c21567_idx'), models.Index(fields=['affected_user', '-timestamp'], name='antoine_aud_affecte_ee4d3d_idx'), models.Index(fields=['event_type', '-timestamp'], name='antoine_aud_event_t_ce4d2f_idx'), models.Index(fields=['severity', '-timestamp'], name='antoine_aud_severit_6b0fc1_idx')],
            },
        ),
    ]
