"""
Password Reset Security Tests

This test suite verifies that the password reset flow is secure and user-friendly.

Security Focus:
- Tokens are secure (HMAC-based, generated by Django)
- Tokens expire after PASSWORD_RESET_TIMEOUT (default 3 days)
- Tokens are one-time use (consumed after reset)
- No user enumeration via error messages
- Password validation enforced
- CSRF protection enabled
- Secure token delivery via email
- Old sessions remain valid after reset

Test Coverage:
- Password reset request flow
- Token generation and validation
- Password reset confirmation
- Password validation rules
- User enumeration prevention
- Token expiration
- Invalid token handling
- Existing functionality preservation
"""

from django.test import TestCase, Client, override_settings
from django.contrib.auth.models import User, Group
from django.contrib.auth.tokens import default_token_generator
from django.urls import reverse
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from django.core import mail
from django.contrib.auth.tokens import default_token_generator, PasswordResetTokenGenerator
import time

# Monkey-patch store_rendered_templates to fix Python 3.14 template context copy issue
from django.test import client
_original_store_rendered_templates = client.store_rendered_templates

def patched_store_rendered_templates(sender, signal, template, context, **kwargs):
    """Patched version that ignores AttributeError when copying context"""
    try:
        return _original_store_rendered_templates(sender, signal, template, context, **kwargs)
    except AttributeError as e:
        if "'super' object has no attribute 'dicts'" in str(e):
            # Python 3.14 compatibility issue - just ignore
            pass
        else:
            raise

client.store_rendered_templates = patched_store_rendered_templates


@override_settings(DEBUG=False)
class PasswordResetSetupTests(TestCase):
    """Setup for password reset tests."""

    def setUp(self):
        """Create test users."""
        self.user_group, _ = Group.objects.get_or_create(name="user")
        
        self.alice = User.objects.create_user('alice', 'alice@example.com', 'Password123!')
        self.alice.groups.add(self.user_group)

        self.client = Client()

    def test_user_exists(self):
        """Verify test user is created."""
        self.assertEqual(User.objects.filter(username='alice').count(), 1)


@override_settings(DEBUG=False)
class PasswordResetRequestTests(TestCase):
    """Test password reset request flow."""

    def setUp(self):
        """Create test users."""
        self.user_group, _ = Group.objects.get_or_create(name="user")
        
        self.alice = User.objects.create_user('alice', 'alice@example.com', 'Password123!')
        self.alice.groups.add(self.user_group)

        self.client = Client()

    def test_password_reset_request_page_loads(self):
        """Password reset request page should load."""
        response = self.client.get(reverse('password_reset'))
        self.assertEqual(response.status_code, 200)
        self.assertIn(b'Password Reset', response.content)

    def test_password_reset_request_with_valid_email(self):
        """Password reset request should work with valid email."""
        # Clear all emails
        mail.outbox = []
        
        response = self.client.post(reverse('password_reset'), {
            'email': 'alice@example.com'
        })
        
        # Should redirect to done page
        self.assertEqual(response.status_code, 302)
        self.assertRedirects(response, reverse('password_reset_done'))
        
        # Email should be sent
        self.assertEqual(len(mail.outbox), 1)
        self.assertIn('alice@example.com', mail.outbox[0].to)

    def test_password_reset_request_with_nonexistent_email(self):
        """Password reset request should not leak if email doesn't exist."""
        mail.outbox = []
        
        response = self.client.post(reverse('password_reset'), {
            'email': 'nonexistent@example.com'
        })
        
        # Should still redirect (no error message about email not found)
        self.assertEqual(response.status_code, 302)
        self.assertRedirects(response, reverse('password_reset_done'))
        
        # No email should be sent for non-existent user
        self.assertEqual(len(mail.outbox), 0)

    def test_password_reset_request_case_insensitive_email(self):
        """Password reset should work with different email cases."""
        mail.outbox = []
        
        response = self.client.post(reverse('password_reset'), {
            'email': 'ALICE@EXAMPLE.COM'  # Uppercase
        })
        
        # Should redirect
        self.assertEqual(response.status_code, 302)
        
        # Email should still be sent (Django normalizes emails)
        self.assertEqual(len(mail.outbox), 1)

    def test_password_reset_done_page_loads(self):
        """Password reset done page should load."""
        response = self.client.get(reverse('password_reset_done'))
        self.assertEqual(response.status_code, 200)
        self.assertIn(b'Password Reset', response.content)

    def test_password_reset_email_contains_token(self):
        """Password reset email should contain reset link."""
        mail.outbox = []
        
        self.client.post(reverse('password_reset'), {
            'email': 'alice@example.com'
        })
        
        # Email should contain reset link
        email = mail.outbox[0]
        self.assertIn('password-reset/', email.body)
        # Should have token
        self.assertIn('/', email.body)  # Token in URL


@override_settings(DEBUG=False)
class PasswordResetConfirmTests(TestCase):
    """Test password reset confirmation flow."""

    def setUp(self):
        """Create test users."""
        self.user_group, _ = Group.objects.get_or_create(name="user")
        
        self.alice = User.objects.create_user('alice', 'alice@example.com', 'OldPassword123!')
        self.alice.groups.add(self.user_group)

        self.client = Client()
        
        # Generate valid reset token
        self.uid = urlsafe_base64_encode(force_bytes(self.alice.pk))
        self.token = default_token_generator.make_token(self.alice)

    def test_password_reset_confirm_page_loads_with_valid_token(self):
        """Password reset confirm page should load with valid token."""
        response = self.client.get(
            reverse('password_reset_confirm', kwargs={'uidb64': self.uid, 'token': self.token})
        )
        
        self.assertEqual(response.status_code, 200)
        self.assertIn(b'password', response.content.lower())

    def test_password_reset_confirm_page_rejects_invalid_token(self):
        """Password reset confirm page should reject invalid token."""
        response = self.client.get(
            reverse('password_reset_confirm', kwargs={'uidb64': self.uid, 'token': 'invalid-token'})
        )
        
        # Should show invalid link message
        self.assertEqual(response.status_code, 200)
        self.assertIn(b'invalid', response.content.lower())

    def test_password_reset_confirm_page_rejects_invalid_uid(self):
        """Password reset confirm page should reject UID."""
        invalid_uid = urlsafe_base64_encode(force_bytes('99999'))
        
        response = self.client.get(
            reverse('password_reset_confirm', kwargs={'uidb64': invalid_uid, 'token': self.token})
        )
        
        # Should show invalid link message
        self.assertEqual(response.status_code, 200)
        self.assertIn(b'invalid', response.content.lower())

    def test_password_reset_confirm_successful(self):
        """Password reset should successfully update password."""
        response = self.client.post(
            reverse('password_reset_confirm', kwargs={'uidb64': self.uid, 'token': self.token}),
            {
                'new_password1': 'NewPassword456!',
                'new_password2': 'NewPassword456!'
            }
        )
        
        # Should redirect to complete page
        self.assertEqual(response.status_code, 302)
        self.assertRedirects(response, reverse('password_reset_complete'))
        
        # User should be able to log in with new password
        self.alice.refresh_from_db()
        self.assertTrue(self.alice.check_password('NewPassword456!'))

    def test_password_reset_confirm_rejects_mismatched_passwords(self):
        """Password reset should reject mismatched passwords."""
        response = self.client.post(
            reverse('password_reset_confirm', kwargs={'uidb64': self.uid, 'token': self.token}),
            {
                'new_password1': 'NewPassword456!',
                'new_password2': 'DifferentPassword456!'
            }
        )
        
        # Should not redirect (stay on form with error)
        self.assertEqual(response.status_code, 200)
        # Error message about passwords not matching
        self.assertIn(b'match', response.content.lower())

    def test_password_reset_confirm_rejects_weak_password(self):
        """Password reset should reject weak passwords."""
        response = self.client.post(
            reverse('password_reset_confirm', kwargs={'uidb64': self.uid, 'token': self.token}),
            {
                'new_password1': '123456',  # Too simple
                'new_password2': '123456'
            }
        )
        
        # Should not redirect (stay on form with error)
        self.assertEqual(response.status_code, 200)
        # Should contain password validation error
        self.assertIn(b'password', response.content.lower())

    def test_password_reset_complete_page_loads(self):
        """Password reset complete page should load."""
        response = self.client.get(reverse('password_reset_complete'))
        self.assertEqual(response.status_code, 200)
        self.assertIn(b'success', response.content.lower())

    def test_password_reset_token_is_one_time_use(self):
        """Password reset token should only be usable once."""
        # First reset
        response1 = self.client.post(
            reverse('password_reset_confirm', kwargs={'uidb64': self.uid, 'token': self.token}),
            {
                'new_password1': 'NewPassword456!',
                'new_password2': 'NewPassword456!'
            }
        )
        self.assertEqual(response1.status_code, 302)
        
        # Try to use same token again (should fail)
        response2 = self.client.get(
            reverse('password_reset_confirm', kwargs={'uidb64': self.uid, 'token': self.token})
        )
        # Should show invalid link (token already consumed)
        self.assertEqual(response2.status_code, 200)
        self.assertIn(b'invalid', response2.content.lower())


@override_settings(DEBUG=False)
class PasswordValidationTests(TestCase):
    """Test password validation in reset flow."""

    def setUp(self):
        """Create test users."""
        self.alice = User.objects.create_user('alice', 'alice@example.com', 'OldPassword123!')
        self.client = Client()
        
        self.uid = urlsafe_base64_encode(force_bytes(self.alice.pk))
        self.token = default_token_generator.make_token(self.alice)

    def test_password_cannot_be_numeric_only(self):
        """Password cannot be entirely numeric."""
        response = self.client.post(
            reverse('password_reset_confirm', kwargs={'uidb64': self.uid, 'token': self.token}),
            {
                'new_password1': '12345678',  # Numeric only
                'new_password2': '12345678'
            }
        )
        
        self.assertEqual(response.status_code, 200)
        self.assertIn(b'password', response.content.lower())

    def test_password_cannot_be_similar_to_username(self):
        """Password cannot be similar to username."""
        response = self.client.post(
            reverse('password_reset_confirm', kwargs={'uidb64': self.uid, 'token': self.token}),
            {
                'new_password1': 'alice12345678',  # Similar to username
                'new_password2': 'alice12345678'
            }
        )
        
        self.assertEqual(response.status_code, 200)
        # May or may not fail depending on Django's similarity check

    def test_password_must_be_minimum_length(self):
        """Password must meet minimum length requirement."""
        response = self.client.post(
            reverse('password_reset_confirm', kwargs={'uidb64': self.uid, 'token': self.token}),
            {
                'new_password1': 'Pass1',  # Too short
                'new_password2': 'Pass1'
            }
        )
        
        self.assertEqual(response.status_code, 200)
        self.assertIn(b'password', response.content.lower())

    def test_strong_password_accepted(self):
        """Strong passwords should be accepted."""
        response = self.client.post(
            reverse('password_reset_confirm', kwargs={'uidb64': self.uid, 'token': self.token}),
            {
                'new_password1': 'SuperSecurePassword123!@#',
                'new_password2': 'SuperSecurePassword123!@#'
            }
        )
        
        # Should redirect to complete page
        self.assertEqual(response.status_code, 302)


@override_settings(DEBUG=False)
class UserEnumerationPreventionTests(TestCase):
    """Test that password reset doesn't leak user existence."""

    def setUp(self):
        """Create test users."""
        self.alice = User.objects.create_user('alice', 'alice@example.com', 'Password123!')
        self.client = Client()

    def test_same_response_for_existing_and_nonexistent_email(self):
        """Should give same response for existing and non-existent emails."""
        client = Client()
        
        # Request for existing email
        response1 = client.post(reverse('password_reset'), {
            'email': 'alice@example.com'
        })
        
        # Request for non-existent email
        response2 = client.post(reverse('password_reset'), {
            'email': 'nonexistent@example.com'
        })
        
        # Both should redirect to done page
        self.assertEqual(response1.status_code, 302)
        self.assertEqual(response2.status_code, 302)
        self.assertEqual(response1.url, response2.url)
        
        # Response text should be same (no error message)
        response1_follow = client.get(response1.url)
        response2_follow = client.get(response2.url)
        self.assertEqual(response1_follow.status_code, response2_follow.status_code)


@override_settings(DEBUG=False)
class PasswordResetSecurityTests(TestCase):
    """Test security aspects of password reset."""

    def setUp(self):
        """Create test users."""
        self.alice = User.objects.create_user('alice', 'alice@example.com', 'OldPassword123!')
        self.client = Client()

    def test_csrf_protection_on_reset_request(self):
        """Password reset request should have CSRF protection."""
        response = self.client.get(reverse('password_reset'))
        self.assertContains(response, 'csrfmiddlewaretoken')

    def test_csrf_protection_on_reset_confirm(self):
        """Password reset confirm should have CSRF protection."""
        uid = urlsafe_base64_encode(force_bytes(self.alice.pk))
        token = default_token_generator.make_token(self.alice)
        
        response = self.client.get(
            reverse('password_reset_confirm', kwargs={'uidb64': uid, 'token': token})
        )
        self.assertContains(response, 'csrfmiddlewaretoken')

    def test_token_expires_after_timeout(self):
        """Token should expire after PASSWORD_RESET_TIMEOUT."""
        # Create an old token (this is complex to test without modifying time)
        # We'll just verify the token generator requires the user's password hash
        
        uid = urlsafe_base64_encode(force_bytes(self.alice.pk))
        token = default_token_generator.make_token(self.alice)
        
        # Change password (invalidates old tokens)
        self.alice.set_password('NewPassword456!')
        self.alice.save()
        
        # Old token should no longer work
        response = self.client.get(
            reverse('password_reset_confirm', kwargs={'uidb64': uid, 'token': token})
        )
        # Should show invalid link
        self.assertEqual(response.status_code, 200)
        self.assertIn(b'invalid', response.content.lower())


@override_settings(DEBUG=False)
class PasswordResetIntegrationTests(TestCase):
    """Test password reset integration with login."""

    def setUp(self):
        """Create test users."""
        self.user_group, _ = Group.objects.get_or_create(name="user")
        
        self.alice = User.objects.create_user('alice', 'alice@example.com', 'OldPassword123!')
        self.alice.groups.add(self.user_group)

        self.client = Client()

    def test_user_can_login_after_password_reset(self):
        """User should be able to log in after password reset."""
        # Reset password
        uid = urlsafe_base64_encode(force_bytes(self.alice.pk))
        token = default_token_generator.make_token(self.alice)
        
        self.client.post(
            reverse('password_reset_confirm', kwargs={'uidb64': uid, 'token': token}),
            {
                'new_password1': 'NewPassword456!',
                'new_password2': 'NewPassword456!'
            }
        )
        
        # Old password should not work
        login_with_old = self.client.login(username='alice', password='OldPassword123!')
        self.assertFalse(login_with_old)
        
        # New password should work
        login_with_new = self.client.login(username='alice', password='NewPassword456!')
        self.assertTrue(login_with_new)
        
        # Should be able to access dashboard
        response = self.client.get(reverse('dashboard'))
        self.assertIn(response.status_code, [200, 302])  # 200 or redirect to login

    def test_password_reset_doesnt_logout_existing_sessions(self):
        """Password reset should not log out other active sessions."""
        # Log in user in one client
        client1 = Client()
        client1.login(username='alice', password='OldPassword123!')
        
        # Reset password in another flow
        client2 = Client()
        uid = urlsafe_base64_encode(force_bytes(self.alice.pk))
        token = default_token_generator.make_token(self.alice)
        
        client2.post(
            reverse('password_reset_confirm', kwargs={'uidb64': uid, 'token': token}),
            {
                'new_password1': 'NewPassword456!',
                'new_password2': 'NewPassword456!'
            }
        )
        
        # First client should still be logged in
        response = client1.get(reverse('dashboard'))
        # Session should still be valid until timeout
        self.assertNotEqual(response.status_code, 403)

    def test_existing_functionality_preserved(self):
        """Existing auth functionality should still work."""
        # Test register
        response = self.client.get(reverse('register'))
        self.assertEqual(response.status_code, 200)
        
        # Test login
        response = self.client.get(reverse('login'))
        self.assertEqual(response.status_code, 200)
        
        # Test password change (requires login)
        self.client.login(username='alice', password='OldPassword123!')
        response = self.client.get(reverse('password_change'))
        self.assertEqual(response.status_code, 200)

    def test_password_reset_confirm_rejects_mismatched_passwords(self):
        """Password reset should reject mismatched passwords."""
        response = self.client.post(
            reverse('password_reset_confirm', kwargs={'uidb64': self.uid, 'token': self.token}),
            {
                'new_password1': 'NewPassword456!',
                'new_password2': 'DifferentPassword456!'
            }
        )
        
        # Should not redirect (stay on form with error)
        self.assertEqual(response.status_code, 200)
        self.assertFormError(response, 'form', 'new_password2', 
                           'The two password fields didn\'t match.')

    def test_password_reset_confirm_rejects_weak_password(self):
        """Password reset should reject weak passwords."""
        response = self.client.post(
            reverse('password_reset_confirm', kwargs={'uidb64': self.uid, 'token': self.token}),
            {
                'new_password1': '123456',  # Too simple
                'new_password2': '123456'
            }
        )
        
        # Should not redirect (stay on form with error)
        self.assertEqual(response.status_code, 200)
        # Should contain password validation error
        self.assertIn(b'password', response.content.lower())

    def test_password_reset_complete_page_loads(self):
        """Password reset complete page should load."""
        response = self.client.get(reverse('password_reset_complete'))
        self.assertEqual(response.status_code, 200)
        self.assertTemplateUsed(response, 'richard_musonera/password_reset_complete.html')

    def test_password_reset_token_is_one_time_use(self):
        """Password reset token should only be usable once."""
        # First reset
        response1 = self.client.post(
            reverse('password_reset_confirm', kwargs={'uidb64': self.uid, 'token': self.token}),
            {
                'new_password1': 'NewPassword456!',
                'new_password2': 'NewPassword456!'
            }
        )
        self.assertEqual(response1.status_code, 302)
        
        # Try to use same token again (should fail)
        response2 = self.client.get(
            reverse('password_reset_confirm', kwargs={'uidb64': self.uid, 'token': self.token})
        )
        # Should show invalid link (token already consumed)
        self.assertEqual(response2.status_code, 200)
        self.assertIn(b'invalid', response2.content.lower())


class PasswordValidationTests(TestCase):
    """Test password validation in reset flow."""

    def setUp(self):
        """Create test users."""
        self.alice = User.objects.create_user('alice', 'alice@example.com', 'OldPassword123!')
        self.client = Client()
        
        self.uid = urlsafe_base64_encode(force_bytes(self.alice.pk))
        self.token = default_token_generator.make_token(self.alice)

    def test_password_cannot_be_numeric_only(self):
        """Password cannot be entirely numeric."""
        response = self.client.post(
            reverse('password_reset_confirm', kwargs={'uidb64': self.uid, 'token': self.token}),
            {
                'new_password1': '12345678',  # Numeric only
                'new_password2': '12345678'
            }
        )
        
        self.assertEqual(response.status_code, 200)
        self.assertIn(b'password', response.content.lower())

    def test_password_cannot_be_similar_to_username(self):
        """Password cannot be similar to username."""
        response = self.client.post(
            reverse('password_reset_confirm', kwargs={'uidb64': self.uid, 'token': self.token}),
            {
                'new_password1': 'alice12345678',  # Similar to username
                'new_password2': 'alice12345678'
            }
        )
        
        self.assertEqual(response.status_code, 200)
        # May or may not fail depending on Django's similarity check

    def test_password_must_be_minimum_length(self):
        """Password must meet minimum length requirement."""
        response = self.client.post(
            reverse('password_reset_confirm', kwargs={'uidb64': self.uid, 'token': self.token}),
            {
                'new_password1': 'Pass1',  # Too short
                'new_password2': 'Pass1'
            }
        )
        
        self.assertEqual(response.status_code, 200)
        self.assertIn(b'password', response.content.lower())

    def test_strong_password_accepted(self):
        """Strong passwords should be accepted."""
        response = self.client.post(
            reverse('password_reset_confirm', kwargs={'uidb64': self.uid, 'token': self.token}),
            {
                'new_password1': 'SuperSecurePassword123!@#',
                'new_password2': 'SuperSecurePassword123!@#'
            }
        )
        
        # Should redirect to complete page
        self.assertEqual(response.status_code, 302)


class UserEnumerationPreventionTests(TestCase):
    """Test that password reset doesn't leak user existence."""

    def setUp(self):
        """Create test users."""
        self.alice = User.objects.create_user('alice', 'alice@example.com', 'Password123!')
        self.client = Client()

    def test_same_response_for_existing_and_nonexistent_email(self):
        """Should give same response for existing and non-existent emails."""
        client = Client()
        
        # Request for existing email
        response1 = client.post(reverse('password_reset'), {
            'email': 'alice@example.com'
        })
        
        # Request for non-existent email
        response2 = client.post(reverse('password_reset'), {
            'email': 'nonexistent@example.com'
        })
        
        # Both should redirect to done page
        self.assertEqual(response1.status_code, 302)
        self.assertEqual(response2.status_code, 302)
        self.assertEqual(response1.url, response2.url)
        
        # Response text should be same (no error message)
        response1_follow = client.get(response1.url)
        response2_follow = client.get(response2.url)
        self.assertEqual(response1_follow.status_code, response2_follow.status_code)


class PasswordResetSecurityTests(TestCase):
    """Test security aspects of password reset."""

    def setUp(self):
        """Create test users."""
        self.alice = User.objects.create_user('alice', 'alice@example.com', 'OldPassword123!')
        self.client = Client()

    def test_csrf_protection_on_reset_request(self):
        """Password reset request should have CSRF protection."""
        response = self.client.get(reverse('password_reset'))
        self.assertContains(response, 'csrfmiddlewaretoken')

    def test_csrf_protection_on_reset_confirm(self):
        """Password reset confirm should have CSRF protection."""
        uid = urlsafe_base64_encode(force_bytes(self.alice.pk))
        token = default_token_generator.make_token(self.alice)
        
        response = self.client.get(
            reverse('password_reset_confirm', kwargs={'uidb64': uid, 'token': token})
        )
        self.assertContains(response, 'csrfmiddlewaretoken')

    def test_token_expires_after_timeout(self):
        """Token should expire after PASSWORD_RESET_TIMEOUT."""
        # Create an old token (this is complex to test without modifying time)
        # We'll just verify the token generator requires the user's password hash
        
        uid = urlsafe_base64_encode(force_bytes(self.alice.pk))
        token = default_token_generator.make_token(self.alice)
        
        # Change password (invalidates old tokens)
        self.alice.set_password('NewPassword456!')
        self.alice.save()
        
        # Old token should no longer work
        response = self.client.get(
            reverse('password_reset_confirm', kwargs={'uidb64': uid, 'token': token})
        )
        # Should show invalid link
        self.assertEqual(response.status_code, 200)
        self.assertIn(b'invalid', response.content.lower())


class PasswordResetIntegrationTests(TestCase):
    """Test password reset integration with login."""

    def setUp(self):
        """Create test users."""
        self.user_group, _ = Group.objects.get_or_create(name="user")
        
        self.alice = User.objects.create_user('alice', 'alice@example.com', 'OldPassword123!')
        self.alice.groups.add(self.user_group)

        self.client = Client()

    def test_user_can_login_after_password_reset(self):
        """User should be able to log in after password reset."""
        # Reset password
        uid = urlsafe_base64_encode(force_bytes(self.alice.pk))
        token = default_token_generator.make_token(self.alice)
        
        self.client.post(
            reverse('password_reset_confirm', kwargs={'uidb64': uid, 'token': token}),
            {
                'new_password1': 'NewPassword456!',
                'new_password2': 'NewPassword456!'
            }
        )
        
        # Old password should not work
        login_with_old = self.client.login(username='alice', password='OldPassword123!')
        self.assertFalse(login_with_old)
        
        # New password should work
        login_with_new = self.client.login(username='alice', password='NewPassword456!')
        self.assertTrue(login_with_new)
        
        # Should be able to access dashboard
        response = self.client.get(reverse('dashboard'))
        self.assertIn(response.status_code, [200, 302])  # 200 or redirect to login

    def test_password_reset_doesnt_logout_existing_sessions(self):
        """Password reset should not log out other active sessions."""
        # Log in user in one client
        client1 = Client()
        client1.login(username='alice', password='OldPassword123!')
        
        # Reset password in another flow
        client2 = Client()
        uid = urlsafe_base64_encode(force_bytes(self.alice.pk))
        token = default_token_generator.make_token(self.alice)
        
        client2.post(
            reverse('password_reset_confirm', kwargs={'uidb64': uid, 'token': token}),
            {
                'new_password1': 'NewPassword456!',
                'new_password2': 'NewPassword456!'
            }
        )
        
        # First client should still be logged in
        response = client1.get(reverse('dashboard'))
        # Session should still be valid until timeout
        self.assertNotEqual(response.status_code, 403)

    def test_existing_functionality_preserved(self):
        """Existing auth functionality should still work."""
        # Test register
        response = self.client.get(reverse('register'))
        self.assertEqual(response.status_code, 200)
        
        # Test login
        response = self.client.get(reverse('login'))
        self.assertEqual(response.status_code, 200)
        
        # Test password change (requires login)
        self.client.login(username='alice', password='OldPassword123!')
        response = self.client.get(reverse('password_change'))
        self.assertEqual(response.status_code, 200)
