# Generated by Django 6.0.4 on 2026-04-17 06:15

import django.db.models.deletion
import justin.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(help_text='Upload a document (pdf, doc, docx, txt, pptx, xlsx). Max 10MB.', upload_to='documents/%Y/%m/%d/', validators=[justin.models.validate_document_file])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('is_public', models.BooleanField(default=False, help_text='Make visible to other users in profiles')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Standard User'), ('instructor', 'Instructor'), ('staff', 'Staff'), ('admin', 'Administrator')], default='user', max_length=20)),
                ('avatar', models.ImageField(blank=True, help_text='Upload a profile avatar image (jpg, png, gif, webp). Max 5MB.', upload_to='avatars/%Y/%m/%d/', validators=[justin.models.validate_avatar_file])),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
