# Generated by Django 6.0.4 on 2026-04-15 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('user', 'Standard User'), ('instructor', 'Instructor'), ('staff', 'Staff'), ('admin', 'Administrator')], default='user', max_length=20),
        ),
    ]
