# Generated by Django 5.2.12 on 2026-04-14 18:55

import niyitegeka.models
import niyitegeka.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niyitegeka', '0002_loginattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to=niyitegeka.models.avatar_upload_path, validators=[niyitegeka.validators.validate_image_extension, niyitegeka.validators.validate_file_size]),
        ),
        migrations.AddField(
            model_name='profile',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=niyitegeka.models.document_upload_path, validators=[niyitegeka.validators.validate_file_extension, niyitegeka.validators.validate_file_size]),
        ),
    ]
