# Generated by Django 6.0.4 on 2026-04-14 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alpha', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': [('can_view_dashboard', 'Can view instructor dashboard')]},
        ),
    ]
