# Generated by Django 6.0.4 on 2026-04-14 19:20

import alpha.models
import alpha.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha', '0002_alter_userprofile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to=alpha.models.user_directory_path, validators=[alpha.validators.validate_file_content, alpha.validators.validate_file_size]),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=alpha.models.user_directory_path, validators=[alpha.validators.validate_file_content, alpha.validators.validate_file_size]),
        ),
    ]
