"""
Django settings for devsec_demo project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
    https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
    https://docs.djangoproject.com/en/6.0/ref/settings/

Security design notes
---------------------
All security-relevant settings are grouped and annotated below.  The key
principles applied:

1. Fail fast on missing secrets — a missing SECRET_KEY raises at startup
   rather than silently running with None (which makes sessions forgeable).
2. Explicit bool for DEBUG — os.environ.get returns a string; the literal
   "False" is truthy, so an explicit membership test is required.
3. ALLOWED_HOSTS from environment — avoids both an empty list (production
   breakage) and a wildcard '*' (host-header injection).
4. Secure cookies — Secure + HttpOnly + SameSite=Lax on both session and
   CSRF cookies; Secure is skipped in local dev (DEBUG=True, no HTTPS).
5. Security headers — X-Content-Type-Options, X-Frame-Options, and
   Referrer-Policy set unconditionally via Django middleware settings.
6. HTTPS transport settings — HSTS and SSL redirect are active only when
   DEBUG=False so local development is not broken.
"""
import os
from pathlib import Path

from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# ── Secret key ────────────────────────────────────────────────────────────────
# FIX: Fail fast if the secret key is missing.
# With SECRET_KEY=None Django accepts any signed value (sessions, CSRF tokens,
# password-reset links) because HMAC(None, …) always produces the same result.
# Generate a key with:
#   python -c "from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())"
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')
if not SECRET_KEY:
    raise ValueError(
        "DJANGO_SECRET_KEY environment variable is not set. "
        "Add it to your .env file before starting the server."
    )

# ── Debug mode ────────────────────────────────────────────────────────────────
# FIX: Convert the env-var string to a real Python bool.
# os.environ.get always returns a string (or None).  Any non-empty string —
# including the literal "False" — is truthy, so naive truthiness tests break.
# Explicit membership against known 'true' values is the safe pattern.
DEBUG = os.environ.get('DJANGO_DEBUG', '').lower() in ('1', 'true', 'yes')

# ── Allowed hosts ─────────────────────────────────────────────────────────────
# FIX: ALLOWED_HOSTS must be explicit.
# An empty list works only because DEBUG=True silently exempts localhost.
# In production (DEBUG=False) every request is rejected with 400 Bad Request
# unless at least one host is listed.  Read from the environment so the same
# settings file works in all environments without modification.
_raw_hosts = os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1')
ALLOWED_HOSTS = [h.strip() for h in _raw_hosts.split(',') if h.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'uwamahoro_joseline',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'devsec_demo.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'devsec_demo.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Media files (user uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# ── Cookie security ───────────────────────────────────────────────────────────
# FIX: Harden session and CSRF cookies.
#
# Secure=True  — cookie is never sent over plain HTTP; prevents network
#                eavesdropping.  Disabled in local dev (DEBUG=True) because
#                the dev server runs on http://localhost without TLS.
# HttpOnly=True — JavaScript cannot access the cookie via document.cookie;
#                 even if XSS executes, the session token stays hidden.
# SameSite=Lax  — cookie is sent on same-site requests and on top-level
#                 cross-site GET navigations (e.g. clicking a link), but
#                 NOT on cross-site POST/PUT/DELETE.  This blocks CSRF via
#                 form submissions from attacker-controlled pages.
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'


# ── Security headers ──────────────────────────────────────────────────────────
# FIX: Enable security headers via SecurityMiddleware and XFrameOptionsMiddleware.
#
# SECURE_CONTENT_TYPE_NOSNIFF — emits X-Content-Type-Options: nosniff.
#   Prevents browsers from MIME-sniffing a response away from the declared
#   Content-Type.  Without this, an uploaded .jpg containing HTML could be
#   served as text/html and execute attacker scripts.
#
# X_FRAME_OPTIONS='DENY' — emits X-Frame-Options: DENY via
#   XFrameOptionsMiddleware.  Prevents the site from being embedded in
#   <iframe>, <frame>, or <object> tags on any origin (clickjacking defence).
#
# SECURE_REFERRER_POLICY — emits Referrer-Policy header.
#   'strict-origin-when-cross-origin': sends full URL for same-origin requests
#   but only the bare origin for cross-origin ones.  Prevents tokens or IDs
#   in query strings from leaking to third-party servers via the Referer header.
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'


# ── HTTPS transport (production only) ────────────────────────────────────────
# FIX: Enable HTTPS enforcement in production.  These settings are active only
# when DEBUG=False so local development (http://localhost) continues to work.
#
# SECURE_SSL_REDIRECT — redirect all HTTP requests to HTTPS.
# SECURE_HSTS_SECONDS — instruct browsers to connect via HTTPS only for one
#   year.  Only enable after confirming HTTPS works; a misconfigured HSTS header
#   can lock users out if the certificate expires or is revoked.
# SECURE_HSTS_INCLUDE_SUBDOMAINS — extend HSTS to all subdomains.
# SECURE_HSTS_PRELOAD — eligible for browser HSTS preload lists.
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000          # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True


# ── Audit Logging ─────────────────────────────────────────────────────────────
# All security-relevant events are emitted on the "uwamahoro_joseline.audit"
# logger at INFO level.  In production, point the file handler at a path
# outside the web root and set propagate=False so audit records do not bleed
# into the general application log.

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "audit": {
            "format": "[AUDIT] %(asctime)s %(levelname)s %(name)s | %(message)s",
            "datefmt": "%Y-%m-%dT%H:%M:%SZ",
        },
    },
    "handlers": {
        "audit_console": {
            "class": "logging.StreamHandler",
            "formatter": "audit",
        },
    },
    "loggers": {
        "uwamahoro_joseline.audit": {
            "handlers": ["audit_console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}
