"""
Django settings for devsec_demo project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/

Security posture
----------------
All security-sensitive values are read from environment variables so that
secrets never appear in version control.  A .env file is loaded in
development via python-dotenv; production uses real env vars injected by
the deployment platform.

Required environment variables (no defaults, startup fails if absent):
  DJANGO_SECRET_KEY  — cryptographically random string, 50+ chars

Optional environment variables (safe defaults shown):
  DJANGO_DEBUG       — 'True' to enable debug mode (default: False)
  DJANGO_ALLOWED_HOSTS — comma-separated hostnames (default: '' → [] )
  EMAIL_BACKEND      — dotted path to mail backend
  DEFAULT_FROM_EMAIL — sender address for outgoing mail
"""
import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

load_dotenv()

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent


# ---------------------------------------------------------------------------
# Core secrets and deployment mode
# ---------------------------------------------------------------------------

# SECRET_KEY must be provided via environment.  An absent or empty value
# raises ImproperlyConfigured at startup rather than silently using an
# insecure fallback — a missing key is always a configuration error.
_secret_key = os.environ.get('DJANGO_SECRET_KEY', '')
if not _secret_key:
    raise ImproperlyConfigured(
        'DJANGO_SECRET_KEY environment variable is not set. '
        'Generate one with: python -c "from django.core.management.utils '
        'import get_random_secret_key; print(get_random_secret_key())"'
    )
SECRET_KEY = _secret_key

# DEBUG must be explicitly set to the string 'True' to be truthy.
# Any other value (including absent, 'False', '0', '') means False.
# This prevents the common mistake where os.environ.get('DJANGO_DEBUG')
# returns None (falsy) in dev but the string 'False' (truthy!) in prod.
DEBUG = os.environ.get('DJANGO_DEBUG', 'False') == 'True'

# ALLOWED_HOSTS comes from a comma-separated env var.  An empty string
# produces an empty list, which Django requires in production (DEBUG=False).
_raw_hosts = os.environ.get('DJANGO_ALLOWED_HOSTS', '')
ALLOWED_HOSTS = [h.strip() for h in _raw_hosts.split(',') if h.strip()]


# ---------------------------------------------------------------------------
# Application definition
# ---------------------------------------------------------------------------

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'webwi',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'devsec_demo.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'devsec_demo.wsgi.application'


# ---------------------------------------------------------------------------
# Database
# ---------------------------------------------------------------------------

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# ---------------------------------------------------------------------------
# Password validation
# ---------------------------------------------------------------------------

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# ---------------------------------------------------------------------------
# Internationalisation
# ---------------------------------------------------------------------------

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# ---------------------------------------------------------------------------
# Static and media files
# ---------------------------------------------------------------------------

STATIC_URL = 'static/'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# ---------------------------------------------------------------------------
# Auth redirect URLs
# ---------------------------------------------------------------------------

LOGIN_URL = 'webwi:login'
LOGIN_REDIRECT_URL = 'webwi:dashboard'
LOGOUT_REDIRECT_URL = 'webwi:login'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ---------------------------------------------------------------------------
# Email
# ---------------------------------------------------------------------------

EMAIL_BACKEND = os.environ.get(
    'EMAIL_BACKEND',
    'django.core.mail.backends.console.EmailBackend',
)
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'noreply@uas.local')

# Password-reset tokens expire after 1 hour.
PASSWORD_RESET_TIMEOUT = 3600


# ---------------------------------------------------------------------------
# Cookie security
#
# Secure flag: ensures cookies are only transmitted over HTTPS.
# HttpOnly flag: blocks JavaScript from reading the cookie value,
#   preventing session token theft via XSS.
# SameSite=Lax: cookies are sent on same-site navigations and top-level
#   cross-site GET requests, but not cross-site POST — mitigates CSRF
#   as a defence-in-depth layer alongside the CSRF middleware.
# ---------------------------------------------------------------------------

SESSION_COOKIE_SECURE = not DEBUG      # HTTPS-only in production
SESSION_COOKIE_HTTPONLY = True         # not readable by JavaScript
SESSION_COOKIE_SAMESITE = 'Lax'        # CSRF mitigation layer

CSRF_COOKIE_SECURE = not DEBUG         # HTTPS-only in production
CSRF_COOKIE_HTTPONLY = False           # JS must read it to attach as header
CSRF_COOKIE_SAMESITE = 'Lax'


# ---------------------------------------------------------------------------
# Transport security
#
# SSL redirect: forces all HTTP requests to HTTPS at the Django layer.
# HSTS: instructs browsers to only connect over HTTPS for one year,
#   including subdomains, and opts into browser preload lists.
# Content-type nosniff: prevents browsers from MIME-sniffing responses away
#   from the declared Content-Type, blocking drive-by-download attacks.
# Referrer policy: limits how much of the current URL is sent in the
#   Referer header to cross-origin destinations.
# ---------------------------------------------------------------------------

SECURE_SSL_REDIRECT = not DEBUG                    # redirect HTTP→HTTPS in prod
SECURE_HSTS_SECONDS = 0 if DEBUG else 31_536_000   # 1 year in production
SECURE_HSTS_INCLUDE_SUBDOMAINS = not DEBUG
SECURE_HSTS_PRELOAD = not DEBUG
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = 'same-origin'

# If running behind a trusted reverse proxy that terminates SSL, uncomment
# and set the header your proxy forwards:
# SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Clickjacking protection (also provided by XFrameOptionsMiddleware).
X_FRAME_OPTIONS = 'DENY'


# ---------------------------------------------------------------------------
# Audit logging
# ---------------------------------------------------------------------------

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'audit': {
            'format': '%(asctime)s [AUDIT] %(levelname)s %(message)s',
            'datefmt': '%Y-%m-%dT%H:%M:%S',
        },
    },
    'handlers': {
        'audit_console': {
            'class': 'logging.StreamHandler',
            'formatter': 'audit',
        },
    },
    'loggers': {
        'webwi.audit': {
            'handlers': ['audit_console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}
