# Generated by Django 6.0.4 on 2026-04-15 13:35

import django.db.models.deletion
import mucyo_aime_maxime_app.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/%d/', validators=[mucyo_aime_maxime_app.models.validate_file_size, mucyo_aime_maxime_app.models.validate_is_image])),
                ('document', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d/', validators=[mucyo_aime_maxime_app.models.validate_file_size, mucyo_aime_maxime_app.models.validate_is_document])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
