# Generated by Django 4.2.7 on 2026-04-15 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uwamahoro_joseline', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': [('can_view_all_profiles', 'Can view all user profiles'), ('can_manage_users', 'Can promote or demote users')]},
        ),
    ]
