# Generated by Django 6.0.4 on 2026-04-14 21:19

import eduard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduard', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=eduard.models.avatar_upload_path),
        ),
    ]
