# Generated by Django 4.2.11 on 2026-04-16 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('richard_musonera', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.FileField(blank=True, help_text='Upload a profile picture (JPG, PNG, GIF - max 5MB)', null=True, upload_to='profile_pictures/%Y/%m/%d/'),
        ),
    ]
