# Generated by Django 4.2.11 on 2026-04-17 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('richard_musonera', '0002_userprofile_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('AUTH_REGISTER', 'User Registration'), ('AUTH_LOGIN_SUCCESS', 'Login Success'), ('AUTH_LOGIN_FAILURE', 'Login Failure'), ('AUTH_LOGOUT', 'Logout'), ('AUTH_PASSWORD_CHANGE', 'Password Changed'), ('AUTH_PASSWORD_RESET_REQUEST', 'Password Reset Request'), ('AUTH_PASSWORD_RESET_CONFIRM', 'Password Reset Confirm'), ('AUTHZ_ROLE_ADD', 'Role Added'), ('AUTHZ_ROLE_REMOVE', 'Role Removed'), ('AUTHZ_ROLE_BULK_CHANGE', 'Roles Changed')], db_index=True, help_text='Type of security event', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the event occurred')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Client IP address', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Client user agent string')),
                ('event_details', models.JSONField(blank=True, default=dict, help_text='Additional event metadata (no sensitive data)')),
                ('success', models.BooleanField(db_index=True, default=True, help_text='Whether the action succeeded')),
                ('error_description', models.TextField(blank=True, help_text='Error message if action failed')),
                ('target_user', models.ForeignKey(blank=True, help_text='User who was the target of the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs_as_target', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs_as_actor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='richard_mus_timesta_77782e_idx'), models.Index(fields=['event_type', '-timestamp'], name='richard_mus_event_t_ff20b5_idx'), models.Index(fields=['user', '-timestamp'], name='richard_mus_user_id_83e585_idx'), models.Index(fields=['target_user', '-timestamp'], name='richard_mus_target__65b582_idx')],
            },
        ),
    ]
